name: Build & Deploy Hugo to gh-pages

on:
  push:
    branches: [ main ]   # ← メインブランチにpushしたら公開
  workflow_dispatch:      # 手動実行も可能

permissions:
  contents: write         # gh-pages へ push に必要

env:
  HUGO_VERSION: 0.150.0   # ← 必要に応じて更新（ローカルが 0.150.0 なら揃える）
  TZ: Asia/Tokyo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true        # テーマをサブモジュール運用する場合は true
          fetch-depth: 0

      - name: Setup Dart Sass (for Hugo Extended)
        run: |
          curl -sLJO https://github.com/sass/dart-sass/releases/download/1.72.0/dart-sass-1.72.0-linux-x64.tar.gz
          sudo tar -C /usr/local -xzf dart-sass-1.72.0-linux-x64.tar.gz
          echo "/usr/local/dart-sass" >> $GITHUB_PATH
          sass --version

      - name: Setup Hugo Extended
        run: |
          curl -sLJO https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.tar.gz
          sudo tar -C /usr/local/bin -xzf hugo_extended_${HUGO_VERSION}_linux-amd64.tar.gz hugo
          hugo version

      - name: Cache Hugo resources
        uses: actions/cache@v4
        with:
          path: |
            resources/_gen
            ~/.cache/hugo_cache
          key: hugo-${{ hashFiles('**/*.scss', '**/*.sass', '**/*.md', 'config.*', 'hugo.*', 'themes/**') }}
          restore-keys: |
            hugo-

      - name: Build site
        run: |
          # CNAME を埋め込みたい場合（独自ドメインに置き換え）:
          echo "nosaerc.com" > ./static/CNAME

          # 本番build（高速＆クリーン）
          hugo --gc --minify

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # 公開/私有どちらでもOK
          publish_dir: ./public
          publish_branch: gh-pages
          # 独自ドメインを自動生成（static/CNAME がある場合は不要）
          cname: nosaerc.com
