baseURL = "https://nosaerc.com/"
title   = "Noah's Ark"
theme   = "PaperMod"
languageCode = "ja"
defaultContentLanguage = "ja"
defaultContentLanguageInSubdir = false

[pagination]
  pagerSize = 10


[markup.goldmark.renderer]
  unsafe = true

[params]
  ShowToc = true
  math = true
  defaultTheme = "light"        # ← ここを light に
  disableThemeToggle = true     # ← 切替ボタンを非表示
  ShowReadingTime = false

[params.homeInfoParams]
  Title = "Noah's Ark"
  Content = "*理性をひっくり返す，思索の方舟*"

assets = [ "css/extended/custom.css" ]

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 10

  [[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 20

  [[menu.main]]
    name = "Music"
    url = "/music/"
    weight = 30

  [[menu.main]]
    name = "Bio"
    url = "/bio/"
    weight = 40

