name: Build & Deploy Hugo to gh-pages

on:
  push:
    branches: [ main ]   # mainにpushしたらデプロイ
  workflow_dispatch:      # 手動実行も可能

permissions:
  contents: write         # gh-pages へ push に必要

env:
  HUGO_VERSION: 0.150.0   # ローカルと合わせる
  TZ: Asia/Tokyo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: ${{ env.HUGO_VERSION }}
          extended: true

      - name: Cache Hugo resources
        uses: actions/cache@v4
        with:
          path: |
            resources/_gen
            ~/.cache/hugo_cache
          key: hugo-${{ hashFiles('**/*.scss', '**/*.sass', '**/*.md', 'config.*', 'hugo.*', 'themes/**') }}
          restore-keys: |
            hugo-

      - name: Build site
        run: |
          echo "nosaerc.com" > ./static/CNAME
          hugo --gc --minify

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          cname: nosaerc.com
